runtime: python27
service: music-practice-log
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /.*
  script: main.app
# [END handlers]


libraries:
  - name: ssl
    version: latest

skip_files:
  - venv/
  - .idea/
  - .git/